### ISSUE TITLE
[U.O.S-Server] 외부 서버 구축 기능 정리 #server_1

### ISSUE THREAD

**Issue by bapmukza9** [UOS2021/U.O.S-Server#1]
### 외부 서버 기능 정리

> | 기능 |   내용  |
> |:-----------:|:---------------------------------------------------------------------------------------------:|
> | 계정 관리 | 앱과 web 통신, 계정 정보는 MySQL DB에 저장 |
> | 요청 처리 | 앱과 POS의 데이터 요청이 들어오면 확인후 응답 신호 발송 |
> | 결제 처리 | POS의 결제 요청 처리, 결제 처리 되면 POS에게 응답 신호 발송 |

### DB 구축
> -  #### customer_account
> ![customer_account](https://user-images.githubusercontent.com/35491052/132522752-ff36c1d7-c82d-4b2c-a3a6-c9366c949ef2.png)
>
> - #### uofpartner_account
> ![uofpartner_account](https://user-images.githubusercontent.com/35491052/132523232-30556b85-2e0f-4336-93cf-8f4552d22d9c.png)
>
> - #### uofpartner_account
> ![order_details](https://user-images.githubusercontent.com/35491052/132523338-9314d9be-cbed-42d5-86bb-ce1150d2c319.png)

**Comment by HyunseungYu** [comment]
확인완료.
